### ISSUE TITLE
A few questions about the provider side of Pact.

### ISSUE THREAD

**Issue by suadev** [pactflow/example-provider-dotnet#12]
Hey @YOU54F, 

Thanks for the repo, it really helps alot!  I have 2 questions. Thank you for you time in advance. 

1) It looks like, i need to run my provider service on localhost before starting provider tests?  If so, how my test will run on CI pipeline?  I mean, i was expecting not to really start my provider service. Maybe a mock server...

```
_providerUri = "http://localhost:9000";
_pactServiceUri = "http://localhost:9001";

```

2) Why we remove products in "AddData" method here? Method name get confused me.  Also, do i really need to access to a real DB?  You know, CDC testing is not integration testing and it runs super fast.  I was expectiong to verify that my response model is the same model that comes from the contract. 

Why do we access to a real DB and why do we need to up and running provider service for contact tests?

```
private void AddData()
{
    _Repository.RemoveProducts();
}

```

**Comment by suadev** [comment]
👀

**Comment by YOU54F** [comment]
Hello sorry for super late replies

> It looks like, i need to run my provider service on localhost before starting provider tests? If so, how my test will run on CI pipeline? I mean, i was expecting not to really start my provider service. Maybe a mock server...

If you can your provider locally, you will be able to run it in CI.

If you use a mock server, you are not verifying your provider implementation and I would argue not getting any benefit from the contracts the consumers have provided in validating that your provider can honour those

In some frameworks you can programatically start up your application (such as NodeJS/Express) as part of your provider test, and close it after the test.

> Why we remove products in "AddData" method here? Method name get confused me.

They actually look like they are mapped incorrectly, I think AddData -> RemoveAllData and RemoveAllData -> AddData

> Also, do i really need to access to a real DB? You know, CDC testing is not integration testing and it runs super fast. I was expectiong to verify that my response model is the same model that comes from the contract.

You can mock out a database if required, if your application uses postgres for example, you can use your own pg database for testing, by changing the endpoint your app calls.

Or you could replace for an in memory database. I would try to maintain calls through your data access repository layer. The more you mock, the less confidence you gain, so its a trade off and balance, depending on circumstances!
