### ISSUE TITLE
Upgrade to .NET 8

### ISSUE THREAD

**Issue by botond-botos-lastpass** [pactflow/example-provider-dotnet#14]
As per [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle) .NET 6 will reach its end of support on November 12, 2024, hence the project should be upgraded to .NET 8, the latest LTS version.

Documentation at https://docs.pactflow.io/docs/examples/dotnet/provider/ should be updated too because it's mentioning .NET Core (3.1).

**Comment by botond-botos-lastpass** [comment]
Please review https://github.com/pactflow/example-provider-dotnet/pull/15

**Comment by YOU54F** [comment]
Fixed by #15, many thanks @botond-botos-lastpass

**Comment by YOU54F** [comment]
the doc sync job is failing as it is trying to write to our main branch for the docs site but its recently been write protected, so I'll need to update that
